### ISSUE TITLE
Error running the CLI

### ISSUE THREAD

**Issue by lourenzo** [goappes/couch-repl#2]
Running the command, the following error is shown.

This is because a callback expects for an argument (couch) that is not defined when called.

```
~/dev/lib/couch-repl/bin/couchrepl:21
        input: couch.stdin,
                    ^
TypeError: Cannot read property 'stdin' of undefined
    at MultiCouch.<anonymous> (~/dev/lib/couch-repl/bin/couchrepl:21:21)
    at MultiCouch.EventEmitter.emit (events.js:92:17)
    at MultiCouch.start (~/dev/lib/couch-repl/node_modules/multicouch/lib/multicouch.js:108:10)
    at Object.<anonymous> (~/dev/lib/couch-repl/bin/couchrepl:30:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by gabrielmancini** [comment]
cool!!!
